services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      tz: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: rest_with_spring_boot_elvis
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - elvis-network
  rest_with_spring_boot_elvis:
    image: elvisassis/rest_with_spring_boot_elvis:v2
    restart: always
    working_dir: /rest_with_spring_boot_elvis
    environment:
      tz: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot_elvis?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 123
    command: mvn spring-boot:run
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - elvis-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    networks:
      - elvis-network
volumes:
  portainer_data:

networks:
  elvis-network:
    driver: bridge
