name: Continuous Integration and Delivery with Github Action

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Application .jar
        working-directory: ./
        run: mvn clean package

      - name: Build Docker Image
        working-directory: ./docker/
        run: docker build -f ../Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_elvis:latest ..


      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_elvis:latest ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_elvis:${{ github.run.id }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_elvis:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_elvis:${{ github.run.id }}
